project_id = "uwzhhzkvqqvaqvkuocrz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enable_signup = true
enable_confirmations = false

[functions.fetch-music-metadata]
verify_jwt = false

[functions.generate-link]
verify_jwt = false

[functions.fanlink-meta]
verify_jwt = false

[functions.presave-meta]
verify_jwt = false

[functions.generate-presave-links]
verify_jwt = false

[functions.auto-resolve-presaves]
verify_jwt = false

[functions.spotify-oauth-callback]
verify_jwt = false

[functions.execute-presave-library-saves]
verify_jwt = false
